import { Toaster } from "@/components/ui/sonner";
import "@/styles/globals.css";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Dogão do Pastor | ERP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_BR">
      <body suppressHydrationWarning={true} suppressContentEditableWarning={true}>
        {children}
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
