import { Toaster } from "@/components/ui/sonner";
import "@/styles/globals.css";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Dogão do Pastor | ERP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="h-full" suppressHydrationWarning>
      <body 
        suppressHydrationWarning={true}
        className="h-full antialiased bg-background"
      >
        {/* Este wrapper garante que nada vaze horizontalmente */}
        <div className="relative flex min-h-screen flex-col overflow-x-hidden">
          <main className="flex-1 w-full max-w-[100vw]">
            {children}
          </main>
        </div>
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}