// src/interfaces/partner.interface.ts

export interface IPartner {
  id: string,
  name: string,
  cnpj: string,
  phone: string,
  description: string,
  website: string,
  facebook: string,
  instagram: string,
  addresInLine: string,
  street: string,
  number: string,
  neighborhood: string,
  city: string,
  state: string,
  zipCode: string,
  complement: string,
  responsibleName: string,
  responsiblePhone: string,
  logo: string | null,
  username: string,
  password: string,
  approved: boolean,
  active: boolean,
  createdAt: Date | string,
  updatedAt: Date | string,
  deletedAt: Date | string | null,
}