export enum CommandStatusEnum {
  PENDING = 'PENDING',
  IN_PRODUCTION = 'IN_PRODUCTION',
  PRODUCED = 'PRODUCED',
  EXPEDITION = 'EXPEDITION',
  QUEUED_FOR_DELIVERY = 'QUEUED_FOR_DELIVERY',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
}
